### ISSUE TITLE
ESP32 JJY電波をBPC電波に変更

### ISSUE THREAD

**Issue by changxinchang** [NeoCat/dotfiles#1]
こんにちは。申し訳ありませんが、このような方法でメッセージをお送りします。 あなたのESP32 JJY電波製作を見て、あなたのチュートリアルに基づいてBPC電波に改造する予定です。 JJY電波の周波数、エンコード方式とBPC電波が全く異なるため、何度も修正しても成功しない。 ご協力をお願いします。
BPC電波の周波数は68.5kHzで、20sごとに完全な時間情報を取得し、1sごとに1つのデータを受信します。データ形式は00012000122023111201です。 0は100msパルス幅、1は200msパルス幅、2は300msパルス幅、3は400msパルス幅を表します。
取得した時間データを68.5kHzキャリアで送信する方法を教えてください。
どうもありがとうございます
![7-1632556068](https://github.com/NeoCat/dotfiles/assets/55017188/d8e75da3-23d9-4755-8ff4-807b0b210db3)

**Comment by NeoCat** [comment]
残念ながら私はBPCについて全く経験がないので、直接お手伝いできることはほとんどないように思います。
一般的な話ですが、電波時計のレシーバモジュールが安価に売られているので、購入して実際にESP32とあなたのプログラムが電波を正しく出しているかを確認したり、実際にBPCを受信した結果と比較してみることは有用でしょう。
また、ESP32のGPIOからは通常極めて弱い電波しか出せません。受信する時計を数cmの近くに置くこと、また時計の感度によっては、GPIOに長い電線を繋ぐこと、トランジスタ等を使って十分な電流を流すことが追加で必要かもしれません。
以上のコメントが参考になれば幸いです。このIssueはクローズします。
